KartingApp.WebUI/Controllers/RaceResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KartingApp.Domain.Abstract;
using KartingApp.Domain.Entities;

namespace KartingApp.WebUI.Controllers
{
    public class RaceResultController : Controller
    {
        private IRaceResultRepository repository;

        public RaceResultController(IRaceResultRepository raceResultRepository)
        {
            repository = raceResultRepository;
        }

        public ViewResult List()
        {
            return View(repository.RaceResults);
        }

        public ViewResult Create(int RaceId = 1)
        {
            ViewData["Driver"] = new SelectList(repository.Drivers.ToList(), "DriverID", "Name");
            ViewData["Race"] = new SelectList(repository.Races.ToList(), "RaceID", "RaceDescription");
            RaceResult rr = new RaceResult();
            rr.RaceID = RaceId;
            return View("Edit", rr);
        }

        [HttpGet]
        public ViewResult Edit(int id = 1)
        {
            RaceResult rr = repository.RaceResults.FirstOrDefault(p => p.RaceResultID == id);

            ViewData["Driver"] = new SelectList(repository.Drivers.ToList(), "DriverID", "Name", rr.DriverID);
            ViewData["Race"] = new SelectList(repository.Races.ToList(), "RaceID", "RaceDescription", rr.RaceID);

            return View("Edit", rr);
        }

        [HttpPost]
        public ActionResult Delete(RaceResult raceResult)
        {
            if (ModelState.IsValid)
            {
                RaceResult rr = repository.RaceResults.FirstOrDefault(p => p.RaceResultID == raceResult.RaceResultID);
                repository.DeleteRaceResult(rr);
                return RedirectToRoute(new { controller = "Race", action = "Edit", id = rr.RaceID });
            }
            else
            {
                RaceResult rr = repository.RaceResults.FirstOrDefault(p => p.RaceResultID == raceResult.RaceResultID);
                return View(rr);
            }
        }

        [HttpPost]
        public ActionResult Edit(RaceResult raceResult)
        {
            if (ModelState.IsValid)
            {
                repository.SaveRaceResult(raceResult);
                TempData["message"] = "RaceResult has been saved.";
                return RedirectToRoute(new { controller = "Race", action = "Edit", id = raceResult.RaceID });
            }
            else
            {
                return Edit(raceResult.RaceResultID);
            }
        }

    }
}

KartingApp.WebUI/Views/RaceResult/Edit.cshtml
@model KartingApp.Domain.Entities.RaceResult

@{
    ViewBag.Title = "Edit RaceResult";
}

@using (Html.BeginForm("Edit", "RaceResult",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary()

    <div>@Html.EditorFor(x => x.RaceResultID)</div>
    <div>@Html.LabelFor(x => x.RaceID)</div>
@*    <div>@Html.EditorFor(x => x.RaceID)</div>*@
    <div>@Html.DropDownListFor(x => x.RaceID, (SelectList)ViewData["Race"], new { @class = "styled-select" })</div>   
    <div>@Html.LabelFor(x => x.DriverID)</div>
@*    <div>@Html.EditorFor(x => x.DriverID)</div>*@
    <div>@Html.DropDownListFor(x => x.DriverID, (SelectList)ViewData["Driver"], new { @class = "styled-select" })</div>
    <div>@Html.LabelFor(x => x.BestLap)</div>
    <div>@Html.EditorFor(x => x.BestLap)</div>

    <br />
    <input type="submit" value="Save" />
}

@using (Html.BeginForm("Delete", "RaceResult",
    FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <div>@Html.EditorFor(x => x.RaceResultID)</div>
    <input type="submit" value="Delete" />
}



<br />@Html.RouteLink("Cancel and return to List", new { controller = "Race", action = "Edit", id = @Model.RaceID })

KartingApp.WebUI/Views/RaceResult/List.cshtml
@model IEnumerable<KartingApp.Domain.Entities.RaceResult>

@{
    ViewBag.Title = "Race Results";
}

<h2>Race Results</h2>
@foreach (var p in Model)
{
    <div>RaceResultID: @p.RaceResultID</div>
    <div>Race Description: @p.Race.RaceDescription</div>
    <div>Driver Name: @p.Driver.Name</div>
    <div>BestLap: @p.BestLap</div>
    @Html.ActionLink("Edit","Edit", new { id=p.RaceResultID })
    <br /><br />
}
    <p>@Html.ActionLink("Add race result", "Create")</p>

    @Html.RouteLink("Menu", new { controller = "Main", action = "Index" })